# GENERATED by scripts/gen-sdk-py.mjs from schema/openrpc.json — DO NOT EDIT.
# apiVersion 1.2.0 · 79 methods (12 stable).
# Regenerate: npm run build:sdk:py. Drift-gated by tests/sdk-py-contract.test.js.
#
# Self-hosted client for the `sesame serve` daemon (JSON-RPC over HTTP). Zero deps (urllib).
# Methods tagged @experimental are outside the API SemVer guarantee.
from __future__ import annotations

import json
import urllib.request
from urllib.parse import quote
from typing import Any, Callable, Literal  # noqa: F401  (Literal used by generated enums)

API_VERSION = "1.2.0"

# Subscribable event topics (event.ready and other broadcast notifications excluded).
SesameEventTopic = Literal["lockState", "deviceUpdate"]


class SesameRpcError(Exception):
    def __init__(self, message: str, code: int, data: dict[str, Any] | None = None) -> None:
        super().__init__(message)
        self.code = code
        self.data = data or {}
        self.kind = self.data.get("kind")
        self.retryable = self.data.get("retryable")


def _omit_none(d: dict[str, Any]) -> dict[str, Any]:
    return {k: v for k, v in d.items() if v is not None}


class _Access:
    def __init__(self, c: "SesameClient") -> None:
        self._c = c

    def clearCards(self, *, deviceUUID: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("access.clearCards", _omit_none({"deviceUUID": deviceUUID, "timeoutMs": timeoutMs}))

    def clearPasscodes(self, *, deviceUUID: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("access.clearPasscodes", _omit_none({"deviceUUID": deviceUUID, "timeoutMs": timeoutMs}))

    def delCards(self, *, items: list[dict[str, Any]]) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("access.delCards", _omit_none({"items": items}))

    def delPasscodes(self, *, items: list[dict[str, Any]]) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("access.delPasscodes", _omit_none({"items": items}))

    def getCards(self, *, deviceUUIDs: list[str], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("access.getCards", _omit_none({"deviceUUIDs": deviceUUIDs, "timeoutMs": timeoutMs}))

    def getPasscodes(self, *, deviceUUIDs: list[str], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("access.getPasscodes", _omit_none({"deviceUUIDs": deviceUUIDs, "timeoutMs": timeoutMs}))

    def postCards(self, *, deviceUUID: str, list: list[dict[str, Any]], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("access.postCards", _omit_none({"deviceUUID": deviceUUID, "list": list, "timeoutMs": timeoutMs}))

    def postPasscodes(self, *, deviceUUID: str, list: list[dict[str, Any]], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("access.postPasscodes", _omit_none({"deviceUUID": deviceUUID, "list": list, "timeoutMs": timeoutMs}))

    def updateCardName(self, *, item: dict[str, Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("access.updateCardName", _omit_none({"item": item, "timeoutMs": timeoutMs}))

    def updateCardOwner(self, *, cardID: str, ownerSubUUID: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("access.updateCardOwner", _omit_none({"cardID": cardID, "ownerSubUUID": ownerSubUUID, "timeoutMs": timeoutMs}))

    def updatePasscodeName(self, *, item: dict[str, Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("access.updatePasscodeName", _omit_none({"item": item, "timeoutMs": timeoutMs}))


class _Account:
    def __init__(self, c: "SesameClient") -> None:
        self._c = c

    def whoami(self, **params: Any) -> Any:
        return self._c._call("account.whoami", params)


class _Company:
    def __init__(self, c: "SesameClient") -> None:
        self._c = c

    def addCompany(self, *, name: str, employeeEmail: str, subUUID: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("company.addCompany", _omit_none({"name": name, "employeeEmail": employeeEmail, "subUUID": subUUID, "timeoutMs": timeoutMs}))

    def getCompanies(self, *, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("company.getCompanies", _omit_none({"timeoutMs": timeoutMs}))

    def getPaymentConfig(self, *, companyID: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("company.getPaymentConfig", _omit_none({"companyID": companyID, "timeoutMs": timeoutMs}))

    def updateCompanyName(self, *, companyID: str, name: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("company.updateCompanyName", _omit_none({"companyID": companyID, "name": name, "timeoutMs": timeoutMs}))


class _Device:
    def __init__(self, c: "SesameClient") -> None:
        self._c = c

    def battery(self, *, deviceUUID: str, pageSize: float | None = None) -> Any:
        return self._c._call("device.battery", _omit_none({"deviceUUID": deviceUUID, "pageSize": pageSize}))

    def history(self, *, deviceUUID: str, pageSize: float | None = None) -> Any:
        return self._c._call("device.history", _omit_none({"deviceUUID": deviceUUID, "pageSize": pageSize}))


class _Devices:
    def __init__(self, c: "SesameClient") -> None:
        self._c = c

    def list(self, **params: Any) -> Any:
        return self._c._call("devices.list", params)


class _Events:
    def __init__(self, c: "SesameClient") -> None:
        self._c = c

    def subscribe(self, *, topics: Any) -> Any:
        return self._c._call("events.subscribe", _omit_none({"topics": topics}))

    def unsubscribe(self, *, topics: Any) -> Any:
        return self._c._call("events.unsubscribe", _omit_none({"topics": topics}))


class _Iot:
    def __init__(self, c: "SesameClient") -> None:
        self._c = c

    def addSesameToHub3(self, *, hub3Id: str, secretKey: str, sesameId: str, ssmSecKa: str, nickName: str | None = None, deviceModel: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("iot.addSesameToHub3", _omit_none({"hub3Id": hub3Id, "secretKey": secretKey, "sesameId": sesameId, "ssmSecKa": ssmSecKa, "nickName": nickName, "deviceModel": deviceModel, "timeoutMs": timeoutMs}))

    def clearHub3WifiSsid(self, *, deviceId: str, secretKey: str, hub3Id: str | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("iot.clearHub3WifiSsid", _omit_none({"deviceId": deviceId, "secretKey": secretKey, "hub3Id": hub3Id}))

    def getMatterPairingCode(self, *, deviceId: str, secretKey: str, hub3Id: str | None = None, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("iot.getMatterPairingCode", _omit_none({"deviceId": deviceId, "secretKey": secretKey, "hub3Id": hub3Id, "timeoutMs": timeoutMs}))

    def hub3RelaySwitch(self, *, deviceId: str, secretKey: str, hub3Id: str | None = None, op: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("iot.hub3RelaySwitch", _omit_none({"deviceId": deviceId, "secretKey": secretKey, "hub3Id": hub3Id, "op": op}))

    def openMatterPairingWindow(self, *, deviceId: str, secretKey: str, hub3Id: str | None = None, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("iot.openMatterPairingWindow", _omit_none({"deviceId": deviceId, "secretKey": secretKey, "hub3Id": hub3Id, "timeoutMs": timeoutMs}))

    def removeSesameFromHub3(self, **params: Any) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("iot.removeSesameFromHub3", params)

    def sendIotCmd(self, *, topic: str, payload: str, op: str | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("iot.sendIotCmd", _omit_none({"topic": topic, "payload": payload, "op": op}))

    def sendIotCmdAwait(self, *, topic: str, payload: str, cmd: float, deviceId: str | None = None, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("iot.sendIotCmdAwait", _omit_none({"topic": topic, "payload": payload, "cmd": cmd, "deviceId": deviceId, "timeoutMs": timeoutMs}))

    def setHub3LedDuty(self, *, deviceId: str, secretKey: str, hub3Id: str | None = None, op: float, duty: float, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("iot.setHub3LedDuty", _omit_none({"deviceId": deviceId, "secretKey": secretKey, "hub3Id": hub3Id, "op": op, "duty": duty, "timeoutMs": timeoutMs}))

    def startFirmwareUpdate(self, *, deviceId: str, hub3Id: str | None = None, secretKey: str) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("iot.startFirmwareUpdate", _omit_none({"deviceId": deviceId, "hub3Id": hub3Id, "secretKey": secretKey}))

    def subscribeIotResponse(self, **params: Any) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("iot.subscribeIotResponse", params)


class _Ir:
    def __init__(self, c: "SesameClient") -> None:
        self._c = c

    def listKeys(self, *, remote: str | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("ir.listKeys", _omit_none({"remote": remote}))

    def send(self, *, remote: str | None = None, key: str) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("ir.send", _omit_none({"remote": remote, "key": key}))


class _Lock:
    def __init__(self, c: "SesameClient") -> None:
        self._c = c

    def click(self, *, name: str | None = None, deviceUUID: str | None = None, secretKey: str | None = None) -> Any:
        return self._c._call("lock.click", _omit_none({"name": name, "deviceUUID": deviceUUID, "secretKey": secretKey}))

    def lock(self, *, name: str | None = None, deviceUUID: str | None = None, secretKey: str | None = None) -> Any:
        return self._c._call("lock.lock", _omit_none({"name": name, "deviceUUID": deviceUUID, "secretKey": secretKey}))

    def status(self, *, deviceUUID: str) -> Any:
        return self._c._call("lock.status", _omit_none({"deviceUUID": deviceUUID}))

    def toggle(self, *, name: str | None = None, deviceUUID: str | None = None, secretKey: str | None = None) -> Any:
        return self._c._call("lock.toggle", _omit_none({"name": name, "deviceUUID": deviceUUID, "secretKey": secretKey}))

    def unlock(self, *, name: str | None = None, deviceUUID: str | None = None, secretKey: str | None = None) -> Any:
        return self._c._call("lock.unlock", _omit_none({"name": name, "deviceUUID": deviceUUID, "secretKey": secretKey}))


class _Org:
    def __init__(self, c: "SesameClient") -> None:
        self._c = c

    def addDeviceGroup(self, *, companyID: str, name: str, uuids: list[str], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.addDeviceGroup", _omit_none({"companyID": companyID, "name": name, "uuids": uuids, "timeoutMs": timeoutMs}))

    def addDeviceInGroup(self, *, companyID: str, gid: str, uuids: list[Any], items: list[Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.addDeviceInGroup", _omit_none({"companyID": companyID, "gid": gid, "uuids": uuids, "items": items, "timeoutMs": timeoutMs}))

    def addEmployeeGroup(self, *, companyID: str, item: dict[str, Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.addEmployeeGroup", _omit_none({"companyID": companyID, "item": item, "timeoutMs": timeoutMs}))

    def addEmployeeInGroup(self, *, companyID: str, gid: str, uuids: list[Any], items: list[Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.addEmployeeInGroup", _omit_none({"companyID": companyID, "gid": gid, "uuids": uuids, "items": items, "timeoutMs": timeoutMs}))

    def addEmployees(self, *, items: list[dict[str, Any]], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.addEmployees", _omit_none({"items": items, "timeoutMs": timeoutMs}))

    def confirmQueryByCS(self, *, email: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.confirmQueryByCS", _omit_none({"email": email, "timeoutMs": timeoutMs}))

    def generateGuestQR(self, *, data: dict[str, Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.generateGuestQR", _omit_none({"data": data, "timeoutMs": timeoutMs}))

    def getCurrentUserInfo(self, *, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.getCurrentUserInfo", _omit_none({"timeoutMs": timeoutMs}))

    def getDeviceEmployeeKeys(self, *, deviceUUID: str, companyID: str, limit: float | None = None, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.getDeviceEmployeeKeys", _omit_none({"deviceUUID": deviceUUID, "companyID": companyID, "limit": limit, "timeoutMs": timeoutMs}))

    def getDeviceGroupBindUserGroup(self, *, gid: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.getDeviceGroupBindUserGroup", _omit_none({"gid": gid, "timeoutMs": timeoutMs}))

    def getDeviceGroups(self, *, companyID: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.getDeviceGroups", _omit_none({"companyID": companyID, "timeoutMs": timeoutMs}))

    def getEmployeeDeviceKeys(self, *, subUUID: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.getEmployeeDeviceKeys", _omit_none({"subUUID": subUUID, "timeoutMs": timeoutMs}))

    def getEmployeeGroupBindDeviceGroup(self, *, gid: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.getEmployeeGroupBindDeviceGroup", _omit_none({"gid": gid, "timeoutMs": timeoutMs}))

    def getEmployeeGroups(self, *, companyID: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.getEmployeeGroups", _omit_none({"companyID": companyID, "timeoutMs": timeoutMs}))

    def getEmployees(self, *, companyID: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.getEmployees", _omit_none({"companyID": companyID, "timeoutMs": timeoutMs}))

    def getTags(self, *, companyID: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.getTags", _omit_none({"companyID": companyID, "timeoutMs": timeoutMs}))

    def postTag(self, *, companyID: str, data: dict[str, Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.postTag", _omit_none({"companyID": companyID, "data": data, "timeoutMs": timeoutMs}))

    def queryByCS(self, *, keyword: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.queryByCS", _omit_none({"keyword": keyword, "timeoutMs": timeoutMs}))

    def removeDeviceGroupBindUserGroup(self, *, companyID: str, data: dict[str, Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.removeDeviceGroupBindUserGroup", _omit_none({"companyID": companyID, "data": data, "timeoutMs": timeoutMs}))

    def removeDeviceGroups(self, *, companyID: str, groupIds: list[dict[str, Any]], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.removeDeviceGroups", _omit_none({"companyID": companyID, "groupIds": groupIds, "timeoutMs": timeoutMs}))

    def removeDeviceInGroup(self, *, companyID: str, gid: str, uuids: list[Any], items: list[dict[str, Any]], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.removeDeviceInGroup", _omit_none({"companyID": companyID, "gid": gid, "uuids": uuids, "items": items, "timeoutMs": timeoutMs}))

    def removeEmployeeDeviceKey(self, *, data: dict[str, Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.removeEmployeeDeviceKey", _omit_none({"data": data, "timeoutMs": timeoutMs}))

    def removeEmployeeGroupBindDeviceGroup(self, *, companyID: str, data: dict[str, Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.removeEmployeeGroupBindDeviceGroup", _omit_none({"companyID": companyID, "data": data, "timeoutMs": timeoutMs}))

    def removeEmployeeGroups(self, *, companyID: str, gids: list[Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.removeEmployeeGroups", _omit_none({"companyID": companyID, "gids": gids, "timeoutMs": timeoutMs}))

    def removeEmployeeInGroup(self, *, companyID: str, gid: str, uuids: list[Any], items: list[dict[str, Any]], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.removeEmployeeInGroup", _omit_none({"companyID": companyID, "gid": gid, "uuids": uuids, "items": items, "timeoutMs": timeoutMs}))

    def removeEmployees(self, *, items: list[dict[str, Any]], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.removeEmployees", _omit_none({"items": items, "timeoutMs": timeoutMs}))

    def removeTag(self, *, companyID: str, data: dict[str, Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.removeTag", _omit_none({"companyID": companyID, "data": data, "timeoutMs": timeoutMs}))

    def reorderEmployees(self, *, items: list[dict[str, Any]], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.reorderEmployees", _omit_none({"items": items, "timeoutMs": timeoutMs}))

    def shareDeviceGroupKeysToEmployeeGroup(self, *, companyID: str, item: dict[str, Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.shareDeviceGroupKeysToEmployeeGroup", _omit_none({"companyID": companyID, "item": item, "timeoutMs": timeoutMs}))

    def shareDeviceKeysToEmployees(self, *, items: list[dict[str, Any]], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.shareDeviceKeysToEmployees", _omit_none({"items": items, "timeoutMs": timeoutMs}))

    def updateDeviceGroup(self, *, companyID: str, item: dict[str, Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.updateDeviceGroup", _omit_none({"companyID": companyID, "item": item, "timeoutMs": timeoutMs}))

    def updateEmployee(self, *, companyID: str, data: dict[str, Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.updateEmployee", _omit_none({"companyID": companyID, "data": data, "timeoutMs": timeoutMs}))

    def updateEmployeeGroup(self, *, companyID: str, item: dict[str, Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.updateEmployeeGroup", _omit_none({"companyID": companyID, "item": item, "timeoutMs": timeoutMs}))

    def updateGuestKeyTag(self, *, data: dict[str, Any], timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("org.updateGuestKeyTag", _omit_none({"data": data, "timeoutMs": timeoutMs}))


class _Presetir:
    def __init__(self, c: "SesameClient") -> None:
        self._c = c

    def emitAir(self, *, deviceId: str, companyID: str, code: float, irDeviceUUID: str | None = None, timeoutMs: float | None = None, power: bool | None = None, temperature: float | None = None, mode: float | None = None, fanSpeed: float | None = None, windDirection: float | None = None, autoSwing: bool | None = None, keyType: str | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("presetir.emitAir", _omit_none({"deviceId": deviceId, "companyID": companyID, "code": code, "irDeviceUUID": irDeviceUUID, "timeoutMs": timeoutMs, "power": power, "temperature": temperature, "mode": mode, "fanSpeed": fanSpeed, "windDirection": windDirection, "autoSwing": autoSwing, "keyType": keyType}))

    def emitButton(self, *, deviceId: str, companyID: str, code: float, irType: float, buttonType: str, irDeviceUUID: str | None = None, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("presetir.emitButton", _omit_none({"deviceId": deviceId, "companyID": companyID, "code": code, "irType": irType, "buttonType": buttonType, "irDeviceUUID": irDeviceUUID, "timeoutMs": timeoutMs}))

    def sendIR(self, *, deviceId: str, command: str, irType: float, companyID: str, irDeviceUUID: str | None = None, operation: str | None = None, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("presetir.sendIR", _omit_none({"deviceId": deviceId, "command": command, "irType": irType, "companyID": companyID, "irDeviceUUID": irDeviceUUID, "operation": operation, "timeoutMs": timeoutMs}))


class _Schedule:
    def __init__(self, c: "SesameClient") -> None:
        self._c = c

    def cancelSchedule(self, *, subUUID: str, scheduleId: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("schedule.cancelSchedule", _omit_none({"subUUID": subUUID, "scheduleId": scheduleId, "timeoutMs": timeoutMs}))

    def getScheduleList(self, *, subUUID: str, timeoutMs: float | None = None) -> Any:
        """@experimental (unverified) — may change without notice."""
        return self._c._call("schedule.getScheduleList", _omit_none({"subUUID": subUUID, "timeoutMs": timeoutMs}))


class SesameClient:
    """Typed client for `sesame serve` (JSON-RPC over HTTP POST /rpc)."""

    def __init__(self, base_url: str, token: str | None = None) -> None:
        self._base_url = base_url.rstrip("/")
        self._token = token
        self._id = 0
        self.access = _Access(self)
        self.account = _Account(self)
        self.company = _Company(self)
        self.device = _Device(self)
        self.devices = _Devices(self)
        self.events = _Events(self)
        self.iot = _Iot(self)
        self.ir = _Ir(self)
        self.lock = _Lock(self)
        self.org = _Org(self)
        self.presetir = _Presetir(self)
        self.schedule = _Schedule(self)

    def _call(self, method: str, params: Any) -> Any:
        self._id += 1
        body = json.dumps({"jsonrpc": "2.0", "id": self._id, "method": method, "params": params}).encode()
        headers = {"content-type": "application/json"}
        if self._token:
            headers["authorization"] = f"Bearer {self._token}"
        req = urllib.request.Request(f"{self._base_url}/rpc", data=body, headers=headers, method="POST")
        with urllib.request.urlopen(req) as resp:
            msg = json.loads(resp.read())
        if "error" in msg and msg["error"] is not None:
            err = msg["error"]
            raise SesameRpcError(err.get("message", "error"), err.get("code", -32000), err.get("data"))
        return msg.get("result")

    def stream_events(self, topics: list[SesameEventTopic], on_event: Callable[[dict[str, Any]], None]) -> None:
        """Stream server-sent events (SSE GET /events). Blocks; calls on_event(frame) per event
        ({"method": "event.<topic>", "params": ...}). The callback also receives event.ready on
        connect. Run in a thread if you need it non-blocking."""
        url = f"{self._base_url}/events?topics={quote(','.join(topics))}"
        headers = {"accept": "text/event-stream"}
        if self._token:
            headers["authorization"] = f"Bearer {self._token}"
        req = urllib.request.Request(url, headers=headers, method="GET")
        with urllib.request.urlopen(req) as resp:
            for raw in resp:
                line = raw.decode("utf-8", "replace").rstrip("\r\n")
                if line.startswith("data:"):  # ":" comment lines (heartbeat) ignored
                    payload = line[5:].strip()
                    if payload:
                        on_event(json.loads(payload))

    def status(self, **params: Any) -> Any:
        return self._call("status", params)
