// sdk eject コマンド (packages/kit/src/cli/sdk.js) のテスト。P2-5 で追加。
//
// テスト戦略:
// - 同梱物の存在と内容確認: readFileSync 直読みで実ファイルシステムを使う。
// - eject の結果確認: spawnSync で実バイナリを呼び、一時ディレクトリへの書き出しを検証する。
//   (ESM namespace は vi.spyOn 不可のため、実ファイルシステムへの書き出しで byte 一致を確認する)
// - 異常系: 未知 lang の exit code と stderr / --json 出力の確認。
//
// 受け入れ基準 (P2-5):
// - eject 出力が同梱物と byte 一致する。
// - 既存 SDK drift gate の green 継続 (別テストファイル sdk-ts-contract / sdk-py-contract)。
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { spawnSync } from "node:child_process";
import { readFileSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const BIN = resolve(__dirname, "../../bin/sesame.js");
const SDK_DIR = resolve(__dirname, "../../sdk");

/** spawnSync ラッパー: node BIN args を実行して { code, stdout, stderr } を返す。 */
function run(args) {
  const r = spawnSync("node", [BIN, ...args], { encoding: "utf8" });
  return { code: r.status ?? 1, stdout: r.stdout ?? "", stderr: r.stderr ?? "" };
}

let work;
beforeEach(() => { work = mkdtempSync(join(tmpdir(), "sesame-eject-")); });
afterEach(() => { rmSync(work, { recursive: true, force: true }); });

// --- 同梱物の存在確認 (packages/kit/sdk/ の物理配置) ---
describe("sdk/ 同梱ファイルが packages/kit/sdk/ に存在する", () => {
  it("ts SDK (sdk/ts/sesame-client.ts) が存在し GENERATED ヘッダを持つ", () => {
    const content = readFileSync(join(SDK_DIR, "ts", "sesame-client.ts"), "utf8");
    expect(content).toContain("GENERATED by scripts/gen-sdk-ts.mjs");
    expect(content).toContain("export class SesameClient");
  });

  it("python SDK (sdk/python/sesame_client.py) が存在し GENERATED ヘッダを持つ", () => {
    const content = readFileSync(join(SDK_DIR, "python", "sesame_client.py"), "utf8");
    expect(content).toContain("GENERATED by scripts/gen-sdk-py.mjs");
    expect(content).toContain("class SesameClient");
  });
});

// --- eject コマンド: byte 一致 ---
describe("sesame sdk eject: 出力が同梱物と byte 一致する", () => {
  it("ts: --out <dir> で sesame-client.ts が書き出され同梱物と一致する", () => {
    const r = run(["sdk", "eject", "ts", "--out", work]);
    expect(r.code).toBe(0);
    const out = readFileSync(join(work, "sesame-client.ts"));
    const expected = readFileSync(join(SDK_DIR, "ts", "sesame-client.ts"));
    expect(out).toEqual(expected);
  });

  it("py: --out <dir> で sesame_client.py が書き出され同梱物と一致する", () => {
    const r = run(["sdk", "eject", "py", "--out", work]);
    expect(r.code).toBe(0);
    const out = readFileSync(join(work, "sesame_client.py"));
    const expected = readFileSync(join(SDK_DIR, "python", "sesame_client.py"));
    expect(out).toEqual(expected);
  });
});

// --- eject コマンド: --json モード ---
describe("sesame sdk eject --json", () => {
  it("ts: --json で ok:true と file パスを stdout に出す", () => {
    const r = run(["sdk", "eject", "ts", "--out", work, "--json"]);
    expect(r.code).toBe(0);
    const out = JSON.parse(r.stdout.trim());
    expect(out.ok).toBe(true);
    expect(out.file).toBe(join(work, "sesame-client.ts"));
  });

  it("py: --json で ok:true と file パスを stdout に出す", () => {
    const r = run(["sdk", "eject", "py", "--out", work, "--json"]);
    expect(r.code).toBe(0);
    const out = JSON.parse(r.stdout.trim());
    expect(out.ok).toBe(true);
    expect(out.file).toBe(join(work, "sesame_client.py"));
  });
});

// --- eject コマンド: 異常系 ---
describe("sesame sdk eject: 未知 lang", () => {
  it("未知 lang は exit 1 で stderr にエラーを出す", () => {
    const r = run(["sdk", "eject", "java"]);
    expect(r.code).toBe(1);
    expect(r.stderr).toContain("Unknown language");
  });

  it("--json + 未知 lang は exit 1 で stdout に ok:false を出す", () => {
    const r = run(["sdk", "eject", "java", "--json"]);
    expect(r.code).toBe(1);
    const out = JSON.parse(r.stdout.trim());
    expect(out.ok).toBe(false);
    expect(typeof out.error).toBe("string");
  });
});

// --- eject コマンド: --help 確認 ---
describe("sesame sdk eject --help", () => {
  it("lang 引数と --out オプションの説明が出る", () => {
    const r = run(["sdk", "eject", "--help"]);
    // help 表示は exit 0 (commander の help は exitOverride で throw → code 0)
    expect(r.code).toBe(0);
    expect(r.stdout).toMatch(/ts\s*\|\s*py/);
  });
});
