// schema/openrpc.json から型付き TypeScript SDK を生成する (packages/kit/sdk/ts/sesame-client.ts)。
//
// スキーマ駆動: 公開契約 (drift gate 済) を唯一の入力にして SDK を機械生成する。
// メソッド追加/変更は build:openrpc → build:sdk で SDK に伝播し、drift gate が同期を担保する。
// experimental メソッドは @experimental JSDoc を付け、stable と型レベルで区別できるようにする。
//
// 実行: npm run build:sdk (build:openrpc の後)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SPEC = resolve(ROOT, "schema", "openrpc.json");
const OUT = resolve(ROOT, "packages", "kit", "sdk", "ts", "sesame-client.ts");

/** OpenRPC param schema → TS 型 (不明は unknown。嘘の型を主張しない)。 */
function tsType(schema) {
  if (!schema || Object.keys(schema).length === 0) return "unknown";
  switch (schema.type) {
    case "string": return schema.enum ? schema.enum.map((v) => JSON.stringify(v)).join(" | ") : "string";
    case "number": return schema.enum ? schema.enum.join(" | ") : "number";
    case "boolean": return "boolean";
    case "array": return `Array<${tsType(schema.items || {})}>`;
    case "object": return "Record<string, unknown>";
    default: return "unknown";
  }
}

/**
 * result schema → TS 型。params の tsType と違い、形不明 (properties 無しの bare object や {}) は
 * unknown にする (「object だ」と嘘をつかない)。properties があれば inline literal で型を出す。
 */
function tsResultType(schema) {
  if (!schema || typeof schema !== "object") return "unknown";
  const base = tsResultTypeBase(schema);
  // nullable:true の result は値が null になりうる (例: lock.status が空なら null)。
  return schema.nullable ? `${base} | null` : base;
}

function tsResultTypeBase(schema) {
  if (schema.properties) {
    const req = schema.required || [];
    const fields = Object.entries(schema.properties).map(([k, v]) => {
      const key = /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k);
      return `${key}${req.includes(k) ? "" : "?"}: ${tsResultType(v)}`;
    });
    return `{ ${fields.join("; ")} }`;
  }
  switch (schema.type) {
    case "string": return schema.enum ? schema.enum.map((v) => JSON.stringify(v)).join(" | ") : "string";
    case "number": return "number";
    case "boolean": return "boolean";
    case "array": return `Array<${tsResultType(schema.items || {})}>`;
    default: return "unknown"; // bare object / 型不明 → unknown
  }
}

/** params 配列 → インライン型リテラル (`{ a: string; b?: number }`)。空なら null。 */
function paramsType(params) {
  if (!params || params.length === 0) return null;
  const fields = params
    .filter((p) => p.name && p.name !== "(params)")
    .map((p) => `${/^[A-Za-z_$][\w$]*$/.test(p.name) ? p.name : JSON.stringify(p.name)}${p.required ? "" : "?"}: ${tsType(p.schema)}`);
  return fields.length ? `{ ${fields.join("; ")} }` : "Record<string, unknown>";
}

/** OpenRPC spec → TS SDK ソース文字列 (決定的)。drift gate がこの純関数を再実行して比較する。 */
export function generateSdk(spec) {
// メソッドを namespace でグループ化 (例: "lock.unlock" → ns "lock"、op "unlock")。
// ドット無し ("status") は ns "" (クライアント直下)。
const groups = new Map();
for (const m of [...spec.methods].sort((a, b) => a.name.localeCompare(b.name))) {
  const dot = m.name.indexOf(".");
  const ns = dot >= 0 ? m.name.slice(0, dot) : "";
  const op = dot >= 0 ? m.name.slice(dot + 1) : m.name;
  if (!groups.has(ns)) groups.set(ns, []);
  groups.get(ns).push({ ...m, op });
}

// field=true: クラス直下フィールド (`op = (..) => ..;`)。false: オブジェクトリテラル要素 (`op: (..) => ..,`)。
function emitMethod(m, indent, field) {
  const pt = paramsType(m.params);
  const arg = pt ? `params: ${pt}` : "";
  const passed = pt ? "params" : "{}";
  const tag = m["x-stability"] === "experimental" ? `${indent}/** @experimental ${m["x-provenance"]} — may change without notice. */\n` : "";
  const safeOp = /^[A-Za-z_$][\w$]*$/.test(m.op) ? m.op : JSON.stringify(m.op);
  const sep = field ? " =" : ":";
  const end = field ? ";" : ",";
  const ret = tsResultType(m.result?.schema);
  return `${tag}${indent}${safeOp}${sep} (${arg}): Promise<${ret}> => this._call(${JSON.stringify(m.name)}, ${passed}) as Promise<${ret}>${end}`;
}

const nsBlocks = [];
for (const [ns, methods] of [...groups].sort((a, b) => a[0].localeCompare(b[0]))) {
  if (ns === "") continue; // ルート直下は後で
  nsBlocks.push(`  readonly ${ns} = {\n${methods.map((m) => emitMethod(m, "    ", false)).join("\n")}\n  };`);
}
const rootMethods = (groups.get("") || []).map((m) => emitMethod(m, "  ", true)).join("\n");

// 購読可能 topic はスキーマの x-event-topics 由来 (event.ready 等の broadcast は含まない)。
// 型もここから導出 = drift gate 対象。
const eventTopics = spec["x-event-topics"] || [];
const eventTopicType = eventTopics.length ? eventTopics.map((t) => JSON.stringify(t)).join(" | ") : "string";

const stableCount = spec.methods.filter((m) => m["x-stability"] === "stable").length;

const out = `// GENERATED by scripts/gen-sdk-ts.mjs from schema/openrpc.json — DO NOT EDIT.
// apiVersion ${spec.info["x-apiVersion"]} · ${spec.methods.length} methods (${stableCount} stable).
// Regenerate: npm run build:sdk. Drift-gated by tests/sdk-ts-contract.test.js.
//
// Self-hosted client for the \`sesame serve\` daemon (JSON-RPC over HTTP).
// Methods tagged @experimental are outside the API SemVer guarantee.

export interface SesameClientOptions {
  /** Daemon base URL, e.g. http://127.0.0.1:8080 */
  baseUrl: string;
  /** Bearer token (printed at daemon startup; ~/.config/sesame-kit/serve.token). */
  token?: string;
  /** Optional fetch impl (defaults to global fetch). */
  fetch?: typeof fetch;
}

export class SesameRpcError extends Error {
  code: number;
  kind?: string;
  retryable?: boolean;
  data?: Record<string, unknown>;
  constructor(message: string, code: number, data?: Record<string, unknown>) {
    super(message);
    this.name = "SesameRpcError";
    this.code = code;
    this.data = data;
    this.kind = data && typeof data.kind === "string" ? data.kind : undefined;
    this.retryable = data && typeof data.retryable === "boolean" ? data.retryable : undefined;
  }
}

export const API_VERSION = ${JSON.stringify(spec.info["x-apiVersion"])};

// HTTP status → error kind/retryable mapping, shared by all four client implementations
// (sdk/ts, sdk/python, clients/js, clients/python). Pinned by tests/fixtures/http-kind-map.json.
//   400/413/415 → bad_params · 401/403 → not_authenticated · 404 → not_implemented
//   408/429/5xx → connection_lost (retryable) · anything else → internal (not retryable)
const HTTP_KIND_BY_STATUS: Record<number, string> = {
  400: "bad_params",
  401: "not_authenticated",
  403: "not_authenticated",
  404: "not_implemented",
  408: "connection_lost",
  413: "bad_params",
  415: "bad_params",
  429: "connection_lost",
};

function httpErrorKind(status: number): string {
  if (status >= 500) return "connection_lost"; // all 5xx are transient from the client's view
  return HTTP_KIND_BY_STATUS[status] ?? "internal";
}

function httpRetryable(status: number): boolean {
  return httpErrorKind(status) === "connection_lost"; // 408/429/5xx; other 4xx are caller errors
}

async function parseResponseJson(res: Response): Promise<unknown> {
  const text = await res.text();
  if (!text) return {};
  try { return JSON.parse(text) as unknown; }
  catch {
    throw new SesameRpcError(\`invalid JSON response from daemon (HTTP \${res.status})\`, -32700,
      { kind: "internal", retryable: false, status: res.status });
  }
}

function httpErrorFromBody(res: Response, body: unknown): SesameRpcError {
  const obj = body && typeof body === "object" ? body as Record<string, unknown> : {};
  const err = obj.error;
  if (err && typeof err === "object") {
    const rpc = err as { code?: unknown; message?: unknown; data?: unknown };
    if (typeof rpc.code === "number" && typeof rpc.message === "string") {
      const data = rpc.data && typeof rpc.data === "object" ? rpc.data as Record<string, unknown> : undefined;
      return new SesameRpcError(rpc.message, rpc.code, data);
    }
  }
  const message = typeof err === "string" ? err
    : typeof obj.message === "string" ? obj.message
      : \`HTTP \${res.status}\`;
  return new SesameRpcError(message, res.status,
    { kind: httpErrorKind(res.status), retryable: httpRetryable(res.status), status: res.status });
}

/** Subscribable event topics (from the schema's x-events). */
export type SesameEventTopic = ${eventTopicType};

/** A server-sent event frame: \`{ method: "event.<topic>", params }\`. */
export interface SesameEvent {
  method: string;
  params: unknown;
}

export class SesameClient {
  private readonly baseUrl: string;
  private readonly token?: string;
  private readonly _fetch: typeof fetch;
  private _id = 0;

  constructor(opts: SesameClientOptions) {
    this.baseUrl = opts.baseUrl.replace(/\\/$/, "");
    this.token = opts.token;
    this._fetch = opts.fetch ?? globalThis.fetch;
  }

  private async _call(method: string, params: unknown): Promise<unknown> {
    const headers: Record<string, string> = { "content-type": "application/json" };
    if (this.token) headers.authorization = \`Bearer \${this.token}\`;
    let res: Response;
    try {
      res = await this._fetch(\`\${this.baseUrl}/rpc\`, {
        method: "POST",
        headers,
        body: JSON.stringify({ jsonrpc: "2.0", id: ++this._id, method, params }),
      });
    } catch (e) {
      const detail = e instanceof Error ? e.message : String(e);
      throw new SesameRpcError(\`cannot reach sesame serve at \${this.baseUrl}: \${detail}\`, -32000,
        { kind: "connection_lost", retryable: true });
    }
    const msg = (await parseResponseJson(res)) as { result?: unknown; error?: { code: number; message: string; data?: Record<string, unknown> } };
    if (!res.ok) throw httpErrorFromBody(res, msg);
    if (msg.error) throw new SesameRpcError(msg.error.message, msg.error.code, msg.error.data);
    return msg.result;
  }

  /**
   * Stream server-sent events (SSE \`GET /events\`). Calls \`onEvent\` per event;
   * resolves when the stream ends. Abort via \`opts.signal\` (AbortController).
   */
  async streamEvents(
    topics: SesameEventTopic[],
    onEvent: (event: SesameEvent) => void,
    opts?: { signal?: AbortSignal },
  ): Promise<void> {
    const headers: Record<string, string> = { accept: "text/event-stream" };
    if (this.token) headers.authorization = \`Bearer \${this.token}\`;
    const url = \`\${this.baseUrl}/events?topics=\${encodeURIComponent(topics.join(","))}\`;
    let res: Response;
    try {
      res = await this._fetch(url, { headers, signal: opts?.signal });
    } catch (e) {
      const detail = e instanceof Error ? e.message : String(e);
      throw new SesameRpcError(\`cannot reach sesame serve at \${this.baseUrl}: \${detail}\`, -32000,
        { kind: "connection_lost", retryable: true });
    }
    if (!res.ok || !res.body) {
      let body: unknown = {};
      try { body = await parseResponseJson(res); } catch { /* keep original HTTP status surface */ }
      throw httpErrorFromBody(res, body);
    }
    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let buf = "";
    for (;;) {
      const { value, done } = await reader.read();
      if (done) break;
      buf += decoder.decode(value, { stream: true });
      const lines = buf.split("\\n");
      buf = lines.pop() ?? ""; // keep the partial trailing line
      for (const line of lines) {
        if (!line.startsWith("data:")) continue; // ":" comments (heartbeat) ignored
        const json = line.slice(5).trim();
        if (json) onEvent(JSON.parse(json) as SesameEvent);
      }
    }
  }

${rootMethods}

${nsBlocks.join("\n\n")}
}
`;
  return out;
}

// CLI 実行時のみ生成・書き出し (import 時は generateSdk だけ使えるよう副作用を出さない)。
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const spec = JSON.parse(readFileSync(SPEC, "utf8"));
  const out = generateSdk(spec);
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, out);
  console.log(`wrote ${OUT} (apiVersion ${spec.info["x-apiVersion"]}, ${spec.methods.length} methods)`);
}
