// GENERATED by scripts/gen-sdk-ts.mjs from schema/openrpc.json — DO NOT EDIT.
// apiVersion 1.2.0 · 79 methods (12 stable).
// Regenerate: npm run build:sdk. Drift-gated by tests/sdk-ts-contract.test.js.
//
// Self-hosted client for the `sesame serve` daemon (JSON-RPC over HTTP).
// Methods tagged @experimental are outside the API SemVer guarantee.

export interface SesameClientOptions {
  /** Daemon base URL, e.g. http://127.0.0.1:8080 */
  baseUrl: string;
  /** Bearer token (printed at daemon startup; ~/.config/sesame-kit/serve.token). */
  token?: string;
  /** Optional fetch impl (defaults to global fetch). */
  fetch?: typeof fetch;
}

export class SesameRpcError extends Error {
  code: number;
  kind?: string;
  retryable?: boolean;
  data?: Record<string, unknown>;
  constructor(message: string, code: number, data?: Record<string, unknown>) {
    super(message);
    this.name = "SesameRpcError";
    this.code = code;
    this.data = data;
    this.kind = data && typeof data.kind === "string" ? data.kind : undefined;
    this.retryable = data && typeof data.retryable === "boolean" ? data.retryable : undefined;
  }
}

export const API_VERSION = "1.2.0";

/** Subscribable event topics (from the schema's x-events). */
export type SesameEventTopic = "lockState" | "deviceUpdate";

/** A server-sent event frame: `{ method: "event.<topic>", params }`. */
export interface SesameEvent {
  method: string;
  params: unknown;
}

export class SesameClient {
  private readonly baseUrl: string;
  private readonly token?: string;
  private readonly _fetch: typeof fetch;
  private _id = 0;

  constructor(opts: SesameClientOptions) {
    this.baseUrl = opts.baseUrl.replace(/\/$/, "");
    this.token = opts.token;
    this._fetch = opts.fetch ?? globalThis.fetch;
  }

  private async _call(method: string, params: unknown): Promise<unknown> {
    const headers: Record<string, string> = { "content-type": "application/json" };
    if (this.token) headers.authorization = `Bearer ${this.token}`;
    const res = await this._fetch(`${this.baseUrl}/rpc`, {
      method: "POST",
      headers,
      body: JSON.stringify({ jsonrpc: "2.0", id: ++this._id, method, params }),
    });
    const msg = (await res.json()) as { result?: unknown; error?: { code: number; message: string; data?: Record<string, unknown> } };
    if (msg.error) throw new SesameRpcError(msg.error.message, msg.error.code, msg.error.data);
    return msg.result;
  }

  /**
   * Stream server-sent events (SSE `GET /events`). Calls `onEvent` per event;
   * resolves when the stream ends. Abort via `opts.signal` (AbortController).
   */
  async streamEvents(
    topics: SesameEventTopic[],
    onEvent: (event: SesameEvent) => void,
    opts?: { signal?: AbortSignal },
  ): Promise<void> {
    const headers: Record<string, string> = { accept: "text/event-stream" };
    if (this.token) headers.authorization = `Bearer ${this.token}`;
    const url = `${this.baseUrl}/events?topics=${encodeURIComponent(topics.join(","))}`;
    const res = await this._fetch(url, { headers, signal: opts?.signal });
    if (!res.ok || !res.body) throw new SesameRpcError(`event stream failed (HTTP ${res.status})`, res.status);
    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let buf = "";
    for (;;) {
      const { value, done } = await reader.read();
      if (done) break;
      buf += decoder.decode(value, { stream: true });
      const lines = buf.split("\n");
      buf = lines.pop() ?? ""; // keep the partial trailing line
      for (const line of lines) {
        if (!line.startsWith("data:")) continue; // ":" comments (heartbeat) ignored
        const json = line.slice(5).trim();
        if (json) onEvent(JSON.parse(json) as SesameEvent);
      }
    }
  }

  status = (): Promise<unknown> => this._call("status", {});

  readonly access = {
    /** @experimental unverified — may change without notice. */
    clearCards: (params: { deviceUUID: string; timeoutMs?: number }): Promise<unknown> => this._call("access.clearCards", params),
    /** @experimental unverified — may change without notice. */
    clearPasscodes: (params: { deviceUUID: string; timeoutMs?: number }): Promise<unknown> => this._call("access.clearPasscodes", params),
    /** @experimental unverified — may change without notice. */
    delCards: (params: { items: Array<Record<string, unknown>> }): Promise<unknown> => this._call("access.delCards", params),
    /** @experimental unverified — may change without notice. */
    delPasscodes: (params: { items: Array<Record<string, unknown>> }): Promise<unknown> => this._call("access.delPasscodes", params),
    /** @experimental unverified — may change without notice. */
    getCards: (params: { deviceUUIDs: Array<string>; timeoutMs?: number }): Promise<unknown> => this._call("access.getCards", params),
    /** @experimental unverified — may change without notice. */
    getPasscodes: (params: { deviceUUIDs: Array<string>; timeoutMs?: number }): Promise<unknown> => this._call("access.getPasscodes", params),
    /** @experimental unverified — may change without notice. */
    postCards: (params: { deviceUUID: string; list: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("access.postCards", params),
    /** @experimental unverified — may change without notice. */
    postPasscodes: (params: { deviceUUID: string; list: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("access.postPasscodes", params),
    /** @experimental unverified — may change without notice. */
    updateCardName: (params: { item: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("access.updateCardName", params),
    /** @experimental unverified — may change without notice. */
    updateCardOwner: (params: { cardID: string; ownerSubUUID: string; timeoutMs?: number }): Promise<unknown> => this._call("access.updateCardOwner", params),
    /** @experimental unverified — may change without notice. */
    updatePasscodeName: (params: { item: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("access.updatePasscodeName", params),
  };

  readonly account = {
    whoami: (): Promise<unknown> => this._call("account.whoami", {}),
  };

  readonly company = {
    /** @experimental unverified — may change without notice. */
    addCompany: (params: { name: string; employeeEmail: string; subUUID: string; timeoutMs?: number }): Promise<unknown> => this._call("company.addCompany", params),
    /** @experimental unverified — may change without notice. */
    getCompanies: (params: { timeoutMs?: number }): Promise<unknown> => this._call("company.getCompanies", params),
    /** @experimental unverified — may change without notice. */
    getPaymentConfig: (params: { companyID: string; timeoutMs?: number }): Promise<unknown> => this._call("company.getPaymentConfig", params),
    /** @experimental unverified — may change without notice. */
    updateCompanyName: (params: { companyID: string; name: string; timeoutMs?: number }): Promise<unknown> => this._call("company.updateCompanyName", params),
  };

  readonly device = {
    battery: (params: { deviceUUID: string; pageSize?: number }): Promise<unknown> => this._call("device.battery", params),
    history: (params: { deviceUUID: string; pageSize?: number }): Promise<unknown> => this._call("device.history", params),
  };

  readonly devices = {
    list: (): Promise<unknown> => this._call("devices.list", {}),
  };

  readonly events = {
    subscribe: (params: { topics: unknown }): Promise<unknown> => this._call("events.subscribe", params),
    unsubscribe: (params: { topics: unknown }): Promise<unknown> => this._call("events.unsubscribe", params),
  };

  readonly iot = {
    /** @experimental unverified — may change without notice. */
    addSesameToHub3: (params: { hub3Id: string; secretKey: string; sesameId: string; ssmSecKa: string; nickName?: string; deviceModel: string; timeoutMs?: number }): Promise<unknown> => this._call("iot.addSesameToHub3", params),
    /** @experimental unverified — may change without notice. */
    clearHub3WifiSsid: (params: { deviceId: string; secretKey: string; hub3Id?: string }): Promise<unknown> => this._call("iot.clearHub3WifiSsid", params),
    /** @experimental unverified — may change without notice. */
    getMatterPairingCode: (params: { deviceId: string; secretKey: string; hub3Id?: string; timeoutMs?: number }): Promise<unknown> => this._call("iot.getMatterPairingCode", params),
    /** @experimental unverified — may change without notice. */
    hub3RelaySwitch: (params: { deviceId: string; secretKey: string; hub3Id?: string; op?: number }): Promise<unknown> => this._call("iot.hub3RelaySwitch", params),
    /** @experimental unverified — may change without notice. */
    openMatterPairingWindow: (params: { deviceId: string; secretKey: string; hub3Id?: string; timeoutMs?: number }): Promise<unknown> => this._call("iot.openMatterPairingWindow", params),
    /** @experimental unverified — may change without notice. */
    removeSesameFromHub3: (params: Record<string, unknown>): Promise<unknown> => this._call("iot.removeSesameFromHub3", params),
    /** @experimental unverified — may change without notice. */
    sendIotCmd: (params: { topic: string; payload: string; op?: string }): Promise<unknown> => this._call("iot.sendIotCmd", params),
    /** @experimental unverified — may change without notice. */
    sendIotCmdAwait: (params: { topic: string; payload: string; cmd: number; deviceId?: string; timeoutMs?: number }): Promise<unknown> => this._call("iot.sendIotCmdAwait", params),
    /** @experimental unverified — may change without notice. */
    setHub3LedDuty: (params: { deviceId: string; secretKey: string; hub3Id?: string; op: number; duty: number; timeoutMs?: number }): Promise<unknown> => this._call("iot.setHub3LedDuty", params),
    /** @experimental unverified — may change without notice. */
    startFirmwareUpdate: (params: { deviceId: string; hub3Id?: string; secretKey: string }): Promise<unknown> => this._call("iot.startFirmwareUpdate", params),
    /** @experimental unverified — may change without notice. */
    subscribeIotResponse: (params: Record<string, unknown>): Promise<unknown> => this._call("iot.subscribeIotResponse", params),
  };

  readonly ir = {
    /** @experimental unverified — may change without notice. */
    listKeys: (params: { remote?: string }): Promise<unknown> => this._call("ir.listKeys", params),
    /** @experimental unverified — may change without notice. */
    send: (params: { remote?: string; key: string }): Promise<unknown> => this._call("ir.send", params),
  };

  readonly lock = {
    click: (params: { name?: string; deviceUUID?: string; secretKey?: string }): Promise<unknown> => this._call("lock.click", params),
    lock: (params: { name?: string; deviceUUID?: string; secretKey?: string }): Promise<unknown> => this._call("lock.lock", params),
    status: (params: { deviceUUID: string }): Promise<unknown> => this._call("lock.status", params),
    toggle: (params: { name?: string; deviceUUID?: string; secretKey?: string }): Promise<unknown> => this._call("lock.toggle", params),
    unlock: (params: { name?: string; deviceUUID?: string; secretKey?: string }): Promise<unknown> => this._call("lock.unlock", params),
  };

  readonly org = {
    /** @experimental unverified — may change without notice. */
    addDeviceGroup: (params: { companyID: string; name: string; uuids: Array<string>; timeoutMs?: number }): Promise<unknown> => this._call("org.addDeviceGroup", params),
    /** @experimental unverified — may change without notice. */
    addDeviceInGroup: (params: { companyID: string; gid: string; uuids: Array<unknown>; items: Array<unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.addDeviceInGroup", params),
    /** @experimental unverified — may change without notice. */
    addEmployeeGroup: (params: { companyID: string; item: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.addEmployeeGroup", params),
    /** @experimental unverified — may change without notice. */
    addEmployeeInGroup: (params: { companyID: string; gid: string; uuids: Array<unknown>; items: Array<unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.addEmployeeInGroup", params),
    /** @experimental unverified — may change without notice. */
    addEmployees: (params: { items: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("org.addEmployees", params),
    /** @experimental unverified — may change without notice. */
    confirmQueryByCS: (params: { email: string; timeoutMs?: number }): Promise<unknown> => this._call("org.confirmQueryByCS", params),
    /** @experimental unverified — may change without notice. */
    generateGuestQR: (params: { data: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.generateGuestQR", params),
    /** @experimental unverified — may change without notice. */
    getCurrentUserInfo: (params: { timeoutMs?: number }): Promise<unknown> => this._call("org.getCurrentUserInfo", params),
    /** @experimental unverified — may change without notice. */
    getDeviceEmployeeKeys: (params: { deviceUUID: string; companyID: string; limit?: number; timeoutMs?: number }): Promise<unknown> => this._call("org.getDeviceEmployeeKeys", params),
    /** @experimental unverified — may change without notice. */
    getDeviceGroupBindUserGroup: (params: { gid: string; timeoutMs?: number }): Promise<unknown> => this._call("org.getDeviceGroupBindUserGroup", params),
    /** @experimental unverified — may change without notice. */
    getDeviceGroups: (params: { companyID: string; timeoutMs?: number }): Promise<unknown> => this._call("org.getDeviceGroups", params),
    /** @experimental unverified — may change without notice. */
    getEmployeeDeviceKeys: (params: { subUUID: string; timeoutMs?: number }): Promise<unknown> => this._call("org.getEmployeeDeviceKeys", params),
    /** @experimental unverified — may change without notice. */
    getEmployeeGroupBindDeviceGroup: (params: { gid: string; timeoutMs?: number }): Promise<unknown> => this._call("org.getEmployeeGroupBindDeviceGroup", params),
    /** @experimental unverified — may change without notice. */
    getEmployeeGroups: (params: { companyID: string; timeoutMs?: number }): Promise<unknown> => this._call("org.getEmployeeGroups", params),
    /** @experimental unverified — may change without notice. */
    getEmployees: (params: { companyID: string; timeoutMs?: number }): Promise<unknown> => this._call("org.getEmployees", params),
    /** @experimental unverified — may change without notice. */
    getTags: (params: { companyID: string; timeoutMs?: number }): Promise<unknown> => this._call("org.getTags", params),
    /** @experimental unverified — may change without notice. */
    postTag: (params: { companyID: string; data: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.postTag", params),
    /** @experimental unverified — may change without notice. */
    queryByCS: (params: { keyword: string; timeoutMs?: number }): Promise<unknown> => this._call("org.queryByCS", params),
    /** @experimental unverified — may change without notice. */
    removeDeviceGroupBindUserGroup: (params: { companyID: string; data: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeDeviceGroupBindUserGroup", params),
    /** @experimental unverified — may change without notice. */
    removeDeviceGroups: (params: { companyID: string; groupIds: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeDeviceGroups", params),
    /** @experimental unverified — may change without notice. */
    removeDeviceInGroup: (params: { companyID: string; gid: string; uuids: Array<unknown>; items: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeDeviceInGroup", params),
    /** @experimental unverified — may change without notice. */
    removeEmployeeDeviceKey: (params: { data: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeEmployeeDeviceKey", params),
    /** @experimental unverified — may change without notice. */
    removeEmployeeGroupBindDeviceGroup: (params: { companyID: string; data: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeEmployeeGroupBindDeviceGroup", params),
    /** @experimental unverified — may change without notice. */
    removeEmployeeGroups: (params: { companyID: string; gids: Array<unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeEmployeeGroups", params),
    /** @experimental unverified — may change without notice. */
    removeEmployeeInGroup: (params: { companyID: string; gid: string; uuids: Array<unknown>; items: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeEmployeeInGroup", params),
    /** @experimental unverified — may change without notice. */
    removeEmployees: (params: { items: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeEmployees", params),
    /** @experimental unverified — may change without notice. */
    removeTag: (params: { companyID: string; data: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeTag", params),
    /** @experimental unverified — may change without notice. */
    reorderEmployees: (params: { items: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("org.reorderEmployees", params),
    /** @experimental unverified — may change without notice. */
    shareDeviceGroupKeysToEmployeeGroup: (params: { companyID: string; item: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.shareDeviceGroupKeysToEmployeeGroup", params),
    /** @experimental unverified — may change without notice. */
    shareDeviceKeysToEmployees: (params: { items: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("org.shareDeviceKeysToEmployees", params),
    /** @experimental unverified — may change without notice. */
    updateDeviceGroup: (params: { companyID: string; item: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.updateDeviceGroup", params),
    /** @experimental unverified — may change without notice. */
    updateEmployee: (params: { companyID: string; data: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.updateEmployee", params),
    /** @experimental unverified — may change without notice. */
    updateEmployeeGroup: (params: { companyID: string; item: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.updateEmployeeGroup", params),
    /** @experimental unverified — may change without notice. */
    updateGuestKeyTag: (params: { data: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.updateGuestKeyTag", params),
  };

  readonly presetir = {
    /** @experimental unverified — may change without notice. */
    emitAir: (params: { deviceId: string; companyID: string; code: number; irDeviceUUID?: string; timeoutMs?: number; power?: boolean; temperature?: number; mode?: number; fanSpeed?: number; windDirection?: number; autoSwing?: boolean; keyType?: string }): Promise<unknown> => this._call("presetir.emitAir", params),
    /** @experimental unverified — may change without notice. */
    emitButton: (params: { deviceId: string; companyID: string; code: number; irType: number; buttonType: string; irDeviceUUID?: string; timeoutMs?: number }): Promise<unknown> => this._call("presetir.emitButton", params),
    /** @experimental unverified — may change without notice. */
    sendIR: (params: { deviceId: string; command: string; irType: number; companyID: string; irDeviceUUID?: string; operation?: string; timeoutMs?: number }): Promise<unknown> => this._call("presetir.sendIR", params),
  };

  readonly schedule = {
    /** @experimental unverified — may change without notice. */
    cancelSchedule: (params: { subUUID: string; scheduleId: string; timeoutMs?: number }): Promise<unknown> => this._call("schedule.cancelSchedule", params),
    /** @experimental unverified — may change without notice. */
    getScheduleList: (params: { subUUID: string; timeoutMs?: number }): Promise<unknown> => this._call("schedule.getScheduleList", params),
  };
}
