// GENERATED by scripts/gen-sdk-ts.mjs from schema/openrpc.json — DO NOT EDIT.
// apiVersion 1.2.0 · 199 methods (13 stable).
// Regenerate: npm run build:sdk. Drift-gated by tests/sdk-ts-contract.test.js.
//
// Self-hosted client for the `sesame serve` daemon (JSON-RPC over HTTP).
// Methods tagged @experimental are outside the API SemVer guarantee.

export interface SesameClientOptions {
  /** Daemon base URL, e.g. http://127.0.0.1:8080 */
  baseUrl: string;
  /** Bearer token (printed at daemon startup; ~/.config/sesame-kit/serve.token). */
  token?: string;
  /** Optional fetch impl (defaults to global fetch). */
  fetch?: typeof fetch;
}

export class SesameRpcError extends Error {
  code: number;
  kind?: string;
  retryable?: boolean;
  data?: Record<string, unknown>;
  constructor(message: string, code: number, data?: Record<string, unknown>) {
    super(message);
    this.name = "SesameRpcError";
    this.code = code;
    this.data = data;
    this.kind = data && typeof data.kind === "string" ? data.kind : undefined;
    this.retryable = data && typeof data.retryable === "boolean" ? data.retryable : undefined;
  }
}

export const API_VERSION = "1.2.0";

// HTTP status → error kind/retryable mapping, shared by all four client implementations
// (sdk/ts, sdk/python, clients/js, clients/python). Canonical table: REFACTORING_PLAN.md
// P4-5/SURF-10, pinned by tests/fixtures/http-kind-map.json.
//   400/413/415 → bad_params · 401/403 → not_authenticated · 404 → not_implemented
//   408/429/5xx → connection_lost (retryable) · anything else → internal (not retryable)
const HTTP_KIND_BY_STATUS: Record<number, string> = {
  400: "bad_params",
  401: "not_authenticated",
  403: "not_authenticated",
  404: "not_implemented",
  408: "connection_lost",
  413: "bad_params",
  415: "bad_params",
  429: "connection_lost",
};

function httpErrorKind(status: number): string {
  if (status >= 500) return "connection_lost"; // all 5xx are transient from the client's view
  return HTTP_KIND_BY_STATUS[status] ?? "internal";
}

function httpRetryable(status: number): boolean {
  return httpErrorKind(status) === "connection_lost"; // 408/429/5xx; other 4xx are caller errors
}

async function parseResponseJson(res: Response): Promise<unknown> {
  const text = await res.text();
  if (!text) return {};
  try { return JSON.parse(text) as unknown; }
  catch {
    throw new SesameRpcError(`invalid JSON response from daemon (HTTP ${res.status})`, -32700,
      { kind: "internal", retryable: false, status: res.status });
  }
}

function httpErrorFromBody(res: Response, body: unknown): SesameRpcError {
  const obj = body && typeof body === "object" ? body as Record<string, unknown> : {};
  const err = obj.error;
  if (err && typeof err === "object") {
    const rpc = err as { code?: unknown; message?: unknown; data?: unknown };
    if (typeof rpc.code === "number" && typeof rpc.message === "string") {
      const data = rpc.data && typeof rpc.data === "object" ? rpc.data as Record<string, unknown> : undefined;
      return new SesameRpcError(rpc.message, rpc.code, data);
    }
  }
  const message = typeof err === "string" ? err
    : typeof obj.message === "string" ? obj.message
      : `HTTP ${res.status}`;
  return new SesameRpcError(message, res.status,
    { kind: httpErrorKind(res.status), retryable: httpRetryable(res.status), status: res.status });
}

/** Subscribable event topics (from the schema's x-events). */
export type SesameEventTopic = "lockState" | "deviceUpdate" | "deviceListChanged";

/** A server-sent event frame: `{ method: "event.<topic>", params }`. */
export interface SesameEvent {
  method: string;
  params: unknown;
}

export class SesameClient {
  private readonly baseUrl: string;
  private readonly token?: string;
  private readonly _fetch: typeof fetch;
  private _id = 0;

  constructor(opts: SesameClientOptions) {
    this.baseUrl = opts.baseUrl.replace(/\/$/, "");
    this.token = opts.token;
    this._fetch = opts.fetch ?? globalThis.fetch;
  }

  private async _call(method: string, params: unknown): Promise<unknown> {
    const headers: Record<string, string> = { "content-type": "application/json" };
    if (this.token) headers.authorization = `Bearer ${this.token}`;
    let res: Response;
    try {
      res = await this._fetch(`${this.baseUrl}/rpc`, {
        method: "POST",
        headers,
        body: JSON.stringify({ jsonrpc: "2.0", id: ++this._id, method, params }),
      });
    } catch (e) {
      const detail = e instanceof Error ? e.message : String(e);
      throw new SesameRpcError(`cannot reach sesame serve at ${this.baseUrl}: ${detail}`, -32000,
        { kind: "connection_lost", retryable: true });
    }
    const msg = (await parseResponseJson(res)) as { result?: unknown; error?: { code: number; message: string; data?: Record<string, unknown> } };
    if (!res.ok) throw httpErrorFromBody(res, msg);
    if (msg.error) throw new SesameRpcError(msg.error.message, msg.error.code, msg.error.data);
    return msg.result;
  }

  /**
   * Stream server-sent events (SSE `GET /events`). Calls `onEvent` per event;
   * resolves when the stream ends. Abort via `opts.signal` (AbortController).
   */
  async streamEvents(
    topics: SesameEventTopic[],
    onEvent: (event: SesameEvent) => void,
    opts?: { signal?: AbortSignal },
  ): Promise<void> {
    const headers: Record<string, string> = { accept: "text/event-stream" };
    if (this.token) headers.authorization = `Bearer ${this.token}`;
    const url = `${this.baseUrl}/events?topics=${encodeURIComponent(topics.join(","))}`;
    let res: Response;
    try {
      res = await this._fetch(url, { headers, signal: opts?.signal });
    } catch (e) {
      const detail = e instanceof Error ? e.message : String(e);
      throw new SesameRpcError(`cannot reach sesame serve at ${this.baseUrl}: ${detail}`, -32000,
        { kind: "connection_lost", retryable: true });
    }
    if (!res.ok || !res.body) {
      let body: unknown = {};
      try { body = await parseResponseJson(res); } catch { /* keep original HTTP status surface */ }
      throw httpErrorFromBody(res, body);
    }
    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let buf = "";
    for (;;) {
      const { value, done } = await reader.read();
      if (done) break;
      buf += decoder.decode(value, { stream: true });
      const lines = buf.split("\n");
      buf = lines.pop() ?? ""; // keep the partial trailing line
      for (const line of lines) {
        if (!line.startsWith("data:")) continue; // ":" comments (heartbeat) ignored
        const json = line.slice(5).trim();
        if (json) onEvent(JSON.parse(json) as SesameEvent);
      }
    }
  }

  status = (): Promise<{ connected: boolean; authState: string; subUUID?: string; apiVersion: string; contractVersion: string }> => this._call("status", {}) as Promise<{ connected: boolean; authState: string; subUUID?: string; apiVersion: string; contractVersion: string }>;

  readonly access = {
    /** @experimental unverified — may change without notice. */
    clearCards: (params: { deviceUUID: string; timeoutMs?: number }): Promise<unknown> => this._call("access.clearCards", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    clearPasscodes: (params: { deviceUUID: string; timeoutMs?: number }): Promise<unknown> => this._call("access.clearPasscodes", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    delCards: (params: { items: Array<Record<string, unknown>> }): Promise<unknown> => this._call("access.delCards", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    deleteAuthenticationData: (params: { operation: string; deviceID: string; items: Array<unknown>; baseUrl?: string }): Promise<unknown> => this._call("access.deleteAuthenticationData", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    delPasscodes: (params: { items: Array<Record<string, unknown>> }): Promise<unknown> => this._call("access.delPasscodes", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getCards: (params: { deviceUUIDs: Array<string>; timeoutMs?: number; graceMs?: number; partialOnTimeout?: boolean }): Promise<unknown> => this._call("access.getCards", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getPasscodes: (params: { deviceUUIDs: Array<string>; timeoutMs?: number; graceMs?: number; partialOnTimeout?: boolean }): Promise<unknown> => this._call("access.getPasscodes", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    postAuthenticationData: (params: { operation: string; deviceID: string; items: Array<unknown>; baseUrl?: string }): Promise<unknown> => this._call("access.postAuthenticationData", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    postCards: (params: { deviceUUID: string; list: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("access.postCards", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    postPasscodes: (params: { deviceUUID: string; list: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("access.postPasscodes", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    putAuthenticationData: (params: { operation: string; deviceID: string; items: Array<unknown>; baseUrl?: string }): Promise<unknown> => this._call("access.putAuthenticationData", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    registerCards: (params: { deviceUUID: string; cards: Array<Record<string, unknown>> }): Promise<unknown> => this._call("access.registerCards", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    registerPasscodes: (params: { deviceUUID: string; passcodes: Array<Record<string, unknown>> }): Promise<unknown> => this._call("access.registerPasscodes", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    updateAuthenticationName: (params: { request?: Record<string, unknown>; kind?: string; baseUrl?: string; subUUID?: string; stpDeviceUUID?: string; name?: string; timestamp?: number; type?: number; cardType?: number; nameUUID?: string; cardNameUUID?: string; faceNameUUID?: string; fingerPrintNameUUID?: string; palmNameUUID?: string; keyBoardPassCodeNameUUID?: string; cardID?: string; faceID?: string; fingerPrintID?: string; palmID?: string; keyBoardPassCode?: string; op?: string }): Promise<unknown> => this._call("access.updateAuthenticationName", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    updateCardName: (params: { item: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("access.updateCardName", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    updateCardOwner: (params: { cardID: string; ownerSubUUID: string; timeoutMs?: number }): Promise<unknown> => this._call("access.updateCardOwner", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    updatePasscodeName: (params: { item: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("access.updatePasscodeName", params) as Promise<unknown>,
  };

  readonly account = {
    whoami: (): Promise<{ customerInfo?: { companyID?: string; subUUID?: string; subscriptionId?: string; name?: string; mainEmail?: string; employeeEmail?: string; employeeName?: string; access?: Array<string>; tag?: Array<string>; isAnonymous?: boolean; isRootUser?: boolean; isSesameApp?: boolean }; quotas?: unknown }> => this._call("account.whoami", {}) as Promise<{ customerInfo?: { companyID?: string; subUUID?: string; subscriptionId?: string; name?: string; mainEmail?: string; employeeEmail?: string; employeeName?: string; access?: Array<string>; tag?: Array<string>; isAnonymous?: boolean; isRootUser?: boolean; isSesameApp?: boolean }; quotas?: unknown }>,
  };

  readonly ble = {
    /** @experimental unverified — may change without notice. */
    "biometric.cardAdd": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; id: Record<string, unknown>; hexName: string }): Promise<unknown> => this._call("ble.biometric.cardAdd", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.cardChange": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; ID: string; hexName: string }): Promise<unknown> => this._call("ble.biometric.cardChange", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.cardChangeValue": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; ID: string; newID: string }): Promise<unknown> => this._call("ble.biometric.cardChangeValue", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.cardDelete": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; cardID: string }): Promise<unknown> => this._call("ble.biometric.cardDelete", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.cardGet": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; collectMs?: number }): Promise<{ records: Array<{ id: string; name?: string; type?: number }> }> => this._call("ble.biometric.cardGet", params) as Promise<{ records: Array<{ id: string; name?: string; type?: number }> }>,
    /** @experimental unverified — may change without notice. */
    "biometric.cardModeGet": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string }): Promise<unknown> => this._call("ble.biometric.cardModeGet", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.cardModeSet": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; mode: number }): Promise<unknown> => this._call("ble.biometric.cardModeSet", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.cardMove": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; cardId: string; touchProUUID: string }): Promise<unknown> => this._call("ble.biometric.cardMove", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.faceChange": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; ID: string; name: string }): Promise<unknown> => this._call("ble.biometric.faceChange", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.faceDelete": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; faceID: string }): Promise<unknown> => this._call("ble.biometric.faceDelete", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.faceListGet": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; collectMs?: number }): Promise<{ records: Array<unknown> }> => this._call("ble.biometric.faceListGet", params) as Promise<{ records: Array<unknown> }>,
    /** @experimental unverified — may change without notice. */
    "biometric.faceModeGet": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string }): Promise<unknown> => this._call("ble.biometric.faceModeGet", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.faceModeSet": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; mode: number }): Promise<unknown> => this._call("ble.biometric.faceModeSet", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.insertSesame": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; sesame: Record<string, unknown> }): Promise<unknown> => this._call("ble.biometric.insertSesame", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.palmDelete": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; palmID: string }): Promise<unknown> => this._call("ble.biometric.palmDelete", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.palmListGet": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; collectMs?: number }): Promise<{ records: Array<unknown> }> => this._call("ble.biometric.palmListGet", params) as Promise<{ records: Array<unknown> }>,
    /** @experimental unverified — may change without notice. */
    "biometric.palmModeGet": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string }): Promise<unknown> => this._call("ble.biometric.palmModeGet", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.palmModeSet": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; mode: number }): Promise<unknown> => this._call("ble.biometric.palmModeSet", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.passcodeAdd": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; id: Record<string, unknown>; hexName: string }): Promise<unknown> => this._call("ble.biometric.passcodeAdd", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.passcodeChange": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; ID: string; hexName: string }): Promise<unknown> => this._call("ble.biometric.passcodeChange", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.passcodeDelete": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; keyBoardPassCodeID: string }): Promise<unknown> => this._call("ble.biometric.passcodeDelete", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.passcodeGet": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; collectMs?: number }): Promise<{ records: Array<{ id: string; name?: string; type?: number }> }> => this._call("ble.biometric.passcodeGet", params) as Promise<{ records: Array<{ id: string; name?: string; type?: number }> }>,
    /** @experimental unverified — may change without notice. */
    "biometric.passcodeModeGet": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string }): Promise<unknown> => this._call("ble.biometric.passcodeModeGet", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.passcodeModeSet": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; mode: number }): Promise<unknown> => this._call("ble.biometric.passcodeModeSet", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.passcodeMove": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; cardId: string; touchProUUID: string }): Promise<unknown> => this._call("ble.biometric.passcodeMove", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.removeSesame": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; tag: string; opts?: Record<string, unknown> }): Promise<unknown> => this._call("ble.biometric.removeSesame", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "biometric.setRadarSensitivity": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; payload: Record<string, unknown> }): Promise<unknown> => this._call("ble.biometric.setRadarSensitivity", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    deleteHistory: (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; historyPayload: Record<string, unknown> }): Promise<unknown> => this._call("ble.deleteHistory", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "fingerPrint.fingerPrintChange": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; ID: string; hexName: string }): Promise<unknown> => this._call("ble.fingerPrint.fingerPrintChange", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "fingerPrint.fingerPrintDelete": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; fingerPrintID: string }): Promise<unknown> => this._call("ble.fingerPrint.fingerPrintDelete", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "fingerPrint.fingerPrintModeGet": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string }): Promise<unknown> => this._call("ble.fingerPrint.fingerPrintModeGet", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "fingerPrint.fingerPrintModeSet": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; mode: number }): Promise<unknown> => this._call("ble.fingerPrint.fingerPrintModeSet", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "fingerPrint.fingerPrints": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; collectMs?: number }): Promise<{ records: Array<{ id: string; name?: string; type?: number }> }> => this._call("ble.fingerPrint.fingerPrints", params) as Promise<{ records: Array<{ id: string; name?: string; type?: number }> }>,
    /** @experimental unverified — may change without notice. */
    getVersionTag: (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string }): Promise<unknown> => this._call("ble.getVersionTag", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    history: (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string }): Promise<unknown> => this._call("ble.history", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "hub3.networkType": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string }): Promise<unknown> => this._call("ble.hub3.networkType", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "hub3.removeSesame": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; tag: string }): Promise<unknown> => this._call("ble.hub3.removeSesame", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "hub3.scanWifiSSID": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string }): Promise<unknown> => this._call("ble.hub3.scanWifiSSID", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "hub3.setWifiPassword": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; password: string }): Promise<unknown> => this._call("ble.hub3.setWifiPassword", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "hub3.setWifiSSID": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; ssid: string }): Promise<unknown> => this._call("ble.hub3.setWifiSSID", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    invoke: (params: { op: string; args?: Array<unknown>; deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string }): Promise<unknown> => this._call("ble.invoke", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    magnet: (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string }): Promise<unknown> => this._call("ble.magnet", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    opSensorControl: (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; seconds: number }): Promise<unknown> => this._call("ble.opSensorControl", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "os2.autolock": (params: { deviceUUID?: string; address?: string; secretKey: string; keyIndex: string; ssmPublicKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; seconds: number; tag?: Record<string, unknown> }): Promise<unknown> => this._call("ble.os2.autolock", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "os2.disableAutolock": (params: { deviceUUID?: string; address?: string; secretKey: string; keyIndex: string; ssmPublicKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; tag?: Record<string, unknown> }): Promise<unknown> => this._call("ble.os2.disableAutolock", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "os2.getAutolock": (params: { deviceUUID?: string; address?: string; secretKey: string; keyIndex: string; ssmPublicKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean }): Promise<unknown> => this._call("ble.os2.getAutolock", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "os2.history": (params: { deviceUUID?: string; address?: string; secretKey: string; keyIndex: string; ssmPublicKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; opts?: Record<string, unknown> }): Promise<unknown> => this._call("ble.os2.history", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "os2.invoke": (params: { op: string; args?: Array<unknown>; deviceUUID?: string; address?: string; secretKey: string; keyIndex: string; ssmPublicKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean }): Promise<unknown> => this._call("ble.os2.invoke", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "os2.register": (params: { deviceUUID: string; address?: string; model?: string; productType?: string; scanTimeoutMs?: number; debug?: boolean; localServerAuth?: boolean; ak?: Record<string, unknown> }): Promise<unknown> => this._call("ble.os2.register", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "os2.updateSetting": (params: { deviceUUID?: string; address?: string; secretKey: string; keyIndex: string; ssmPublicKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; setting: Record<string, unknown>; tag?: Record<string, unknown> }): Promise<unknown> => this._call("ble.os2.updateSetting", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "os2.versionTag": (params: { deviceUUID?: string; address?: string; secretKey: string; keyIndex: string; ssmPublicKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean }): Promise<unknown> => this._call("ble.os2.versionTag", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    position: (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; lockPosition: number; unlockPosition: number }): Promise<{ resultCode: number; resultName: string }> => this._call("ble.position", params) as Promise<{ resultCode: number; resultName: string }>,
    /** @experimental unverified — may change without notice. */
    register: (params: { deviceUUID: string; address?: string; model?: string; productType?: string; scanTimeoutMs?: number; debug?: boolean; nowMs?: number; registerBaseUrl?: string }): Promise<unknown> => this._call("ble.register", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "remoteNano.insertSesame": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; sesame: Record<string, unknown> }): Promise<unknown> => this._call("ble.remoteNano.insertSesame", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "remoteNano.removeSesame": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; tag: string; opts?: Record<string, unknown> }): Promise<unknown> => this._call("ble.remoteNano.removeSesame", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "remoteNano.setRadarSensitivity": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; payload: Record<string, unknown> }): Promise<unknown> => this._call("ble.remoteNano.setRadarSensitivity", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "remoteNano.setTriggerDelayTime": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; time: number }): Promise<unknown> => this._call("ble.remoteNano.setTriggerDelayTime", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    reset: (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string }): Promise<{ resultCode: number; resultName: string }> => this._call("ble.reset", params) as Promise<{ resultCode: number; resultName: string }>,
    /** @experimental unverified — may change without notice. */
    scan: (params: { scanTimeoutMs?: number; includeUnknown?: boolean }): Promise<{ ok: boolean; count: number; devices: Array<{ deviceUUID: string; productType?: number; model?: string | null; kind?: string; isRegistered?: boolean; rssi?: number | null; localName?: string | null; address?: string | null }> }> => this._call("ble.scan", params) as Promise<{ ok: boolean; count: number; devices: Array<{ deviceUUID: string; productType?: number; model?: string | null; kind?: string; isRegistered?: boolean; rssi?: number | null; localName?: string | null; address?: string | null }> }>,
    /** @experimental unverified — may change without notice. */
    "script.click": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; index?: number }): Promise<unknown> => this._call("ble.script.click", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "script.getCurrentScript": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; index?: number }): Promise<unknown> => this._call("ble.script.getCurrentScript", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "script.getScriptNameList": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string }): Promise<unknown> => this._call("ble.script.getScriptNameList", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "script.selectScript": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; index: number }): Promise<unknown> => this._call("ble.script.selectScript", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "script.sendClickScript": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; index: number; script: Record<string, unknown> }): Promise<unknown> => this._call("ble.script.sendClickScript", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    sendAdvProductType: (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; data: Record<string, unknown> }): Promise<unknown> => this._call("ble.sendAdvProductType", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    setBleTxPower: (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; txPower: number }): Promise<unknown> => this._call("ble.setBleTxPower", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    updateFirmware: (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; timeoutMs?: number }): Promise<{ commandSent: boolean; resultCode?: number | null; resultName?: string | null }> => this._call("ble.updateFirmware", params) as Promise<{ commandSent: boolean; resultCode?: number | null; resultName?: string | null }>,
    /** @experimental unverified — may change without notice. */
    "wifi.connect": (params: { deviceUUID?: string; address?: string; secretKey: string; model: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; companyId?: string }): Promise<{ resultCode: number; resultName: string }> => this._call("ble.wifi.connect", params) as Promise<{ resultCode: number; resultName: string }>,
    /** @experimental unverified — may change without notice. */
    "wifi.insertSesames": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; sesameKey: Record<string, unknown> }): Promise<unknown> => this._call("ble.wifi.insertSesames", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "wifi.networkStatus": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string }): Promise<unknown> => this._call("ble.wifi.networkStatus", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "wifi.removeSesame": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; sesameKeyTag: string }): Promise<unknown> => this._call("ble.wifi.removeSesame", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "wifi.reset": (params: { deviceUUID?: string; address?: string; secretKey: string; model?: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string }): Promise<unknown> => this._call("ble.wifi.reset", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    "wifi.scan": (params: { deviceUUID?: string; address?: string; secretKey: string; model: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; companyId?: string; collectMs?: number }): Promise<{ ssids: Array<{ ssid: string; rssi: number }> }> => this._call("ble.wifi.scan", params) as Promise<{ ssids: Array<{ ssid: string; rssi: number }> }>,
    /** @experimental unverified — may change without notice. */
    "wifi.setPassword": (params: { deviceUUID?: string; address?: string; secretKey: string; model: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; password: string; companyId?: string }): Promise<{ resultCode: number; resultName: string }> => this._call("ble.wifi.setPassword", params) as Promise<{ resultCode: number; resultName: string }>,
    /** @experimental unverified — may change without notice. */
    "wifi.setSsid": (params: { deviceUUID?: string; address?: string; secretKey: string; model: string; scanTimeoutMs?: number; debug?: boolean; needAuthFromServer?: boolean; registerBaseUrl?: string; ssid: string; companyId?: string }): Promise<{ resultCode: number; resultName: string }> => this._call("ble.wifi.setSsid", params) as Promise<{ resultCode: number; resultName: string }>,
  };

  readonly cloud = {
    /** @experimental unverified — may change without notice. */
    ping: (): Promise<unknown> => this._call("cloud.ping", {}) as Promise<unknown>,
  };

  readonly company = {
    /** @experimental unverified — may change without notice. */
    addCompany: (params: { name: string; employeeEmail: string; subUUID?: string; timeoutMs?: number }): Promise<unknown> => this._call("company.addCompany", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getCompanies: (params: { timeoutMs?: number }): Promise<unknown> => this._call("company.getCompanies", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getPaymentConfig: (params: { companyID?: string; timeoutMs?: number }): Promise<unknown> => this._call("company.getPaymentConfig", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    updateCompanyName: (params: { companyID?: string; name: string; timeoutMs?: number }): Promise<unknown> => this._call("company.updateCompanyName", params) as Promise<unknown>,
  };

  readonly config = {
    /** @experimental unverified — may change without notice. */
    syncHub3s: (params: { prune?: boolean }): Promise<unknown> => this._call("config.syncHub3s", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    syncLocks: (params: { prune?: boolean }): Promise<unknown> => this._call("config.syncLocks", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    syncRemoteKeys: (params: { remote?: string }): Promise<unknown> => this._call("config.syncRemoteKeys", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    syncRemotes: (): Promise<unknown> => this._call("config.syncRemotes", {}) as Promise<unknown>,
  };

  readonly device = {
    battery: (params: { deviceUUID: string; pageSize?: number; lastEvaluatedKey?: Record<string, unknown> }): Promise<{ records: Array<{ ts: number; light?: number; heavy?: number; lightPercentage?: number; heavyPercentage?: number }>; lastEvaluatedKey?: unknown | null }> => this._call("device.battery", params) as Promise<{ records: Array<{ ts: number; light?: number; heavy?: number; lightPercentage?: number; heavyPercentage?: number }>; lastEvaluatedKey?: unknown | null }>,
    /** @experimental unverified — may change without notice. */
    delete: (params: { deviceUUID: string }): Promise<unknown> => this._call("device.delete", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    hideBattery: (params: { deviceUUID: string; timestampSecond: number }): Promise<unknown> => this._call("device.hideBattery", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    hideHistory: (params: { deviceUUID: string; timestamp: number }): Promise<unknown> => this._call("device.hideHistory", params) as Promise<unknown>,
    history: (params: { deviceUUID: string; pageSize?: number; lastKey?: number }): Promise<Array<{ timestamp: number; device_id?: string; record_id?: string; type: number; history_tag?: string; botHistoryMode?: string; botAlias?: string; botViaType?: number }>> => this._call("device.history", params) as Promise<Array<{ timestamp: number; device_id?: string; record_id?: string; type: number; history_tag?: string; botHistoryMode?: string; botAlias?: string; botViaType?: number }>>,
    /** @experimental unverified — may change without notice. */
    rename: (params: { deviceUUID: string; deviceName: string }): Promise<unknown> => this._call("device.rename", params) as Promise<unknown>,
  };

  readonly devices = {
    /** @experimental unverified — may change without notice. */
    add: (params: { items: Array<Record<string, unknown>> }): Promise<unknown> => this._call("devices.add", params) as Promise<unknown>,
    list: (): Promise<Array<{ deviceUUID: string; deviceName?: string; deviceModel?: string; secretKey?: string; keyLevel?: number; rank?: number; stateInfo?: unknown }>> => this._call("devices.list", {}) as Promise<Array<{ deviceUUID: string; deviceName?: string; deviceModel?: string; secretKey?: string; keyLevel?: number; rank?: number; stateInfo?: unknown }>>,
    /** @experimental unverified — may change without notice. */
    notifyManage: (params: { pushToken: string; deviceUUID: string; enablePush: boolean }): Promise<unknown> => this._call("devices.notifyManage", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    notifyStatus: (params: { pushToken: string; items: Array<Record<string, unknown>> }): Promise<unknown> => this._call("devices.notifyStatus", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    reorder: (params: { items: Array<Record<string, unknown>> }): Promise<unknown> => this._call("devices.reorder", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    switchRecharge: (params: { deviceUUID: string; isRechargeBattery: boolean }): Promise<unknown> => this._call("devices.switchRecharge", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    userList: (): Promise<unknown> => this._call("devices.userList", {}) as Promise<unknown>,
  };

  readonly events = {
    subscribe: (params: { topics: unknown }): Promise<{ subscribed: Array<string> }> => this._call("events.subscribe", params) as Promise<{ subscribed: Array<string> }>,
    unsubscribe: (params: { topics: unknown }): Promise<{ subscribed: Array<string> }> => this._call("events.unsubscribe", params) as Promise<{ subscribed: Array<string> }>,
  };

  readonly firmware = {
    /** @experimental unverified — may change without notice. */
    list: (): Promise<unknown> => this._call("firmware.list", {}) as Promise<unknown>,
  };

  readonly iot = {
    /** @experimental unverified — may change without notice. */
    addSesameToHub3: (params: { hub3Id: string; secretKey: string; sesameId: string; ssmSecKa: string; nickName?: string; deviceModel: string; timeoutMs?: number }): Promise<unknown> => this._call("iot.addSesameToHub3", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    clearHub3WifiSsid: (params: { deviceId: string; secretKey: string; hub3Id?: string }): Promise<unknown> => this._call("iot.clearHub3WifiSsid", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getMatterPairingCode: (params: { deviceId: string; secretKey: string; hub3Id?: string; timeoutMs?: number }): Promise<unknown> => this._call("iot.getMatterPairingCode", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    hub3RelaySwitch: (params: { deviceId: string; secretKey: string; hub3Id?: string; op?: number }): Promise<unknown> => this._call("iot.hub3RelaySwitch", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    openMatterPairingWindow: (params: { deviceId: string; secretKey: string; hub3Id?: string; timeoutMs?: number }): Promise<unknown> => this._call("iot.openMatterPairingWindow", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    removeSesameFromHub3: (params: { hub3Id: string; secretKey: string; sesameId: string; ssmSecKa: string; nickName?: string; deviceModel: string; timeoutMs?: number }): Promise<unknown> => this._call("iot.removeSesameFromHub3", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    sendIotCmd: (params: { topic: string; payload: string; op?: string }): Promise<unknown> => this._call("iot.sendIotCmd", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    sendIotCmdAwait: (params: { topic: string; payload: string; cmd: number; deviceId?: string; timeoutMs?: number }): Promise<unknown> => this._call("iot.sendIotCmdAwait", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    setHub3LedDuty: (params: { deviceId: string; secretKey: string; hub3Id?: string; op: number; duty: number; timeoutMs?: number }): Promise<unknown> => this._call("iot.setHub3LedDuty", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    startFirmwareUpdate: (params: { deviceId: string; hub3Id?: string; secretKey: string }): Promise<unknown> => this._call("iot.startFirmwareUpdate", params) as Promise<unknown>,
  };

  readonly ir = {
    /** @experimental unverified — may change without notice. */
    addRemote: (params: { remote: Record<string, unknown> }): Promise<unknown> => this._call("ir.addRemote", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    addRemoteToMatter: (params: { hub3DeviceId: string; irDeviceType: number; cmdOn: string; cmdOff: string; irDeviceUUID: string; irDeviceName: string }): Promise<unknown> => this._call("ir.addRemoteToMatter", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    deleteKey: (params: { remote: string; key: string }): Promise<unknown> => this._call("ir.deleteKey", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    deleteRemote: (params: { remote: string }): Promise<unknown> => this._call("ir.deleteRemote", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getMode: (params: { hub3?: string }): Promise<unknown> => this._call("ir.getMode", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    learn: (params: { remote: string; key: string; timeoutMs?: number }): Promise<unknown> => this._call("ir.learn", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    listKeys: (params: { remote?: string; hub3DeviceId?: string; irDeviceUUID?: string }): Promise<unknown> => this._call("ir.listKeys", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    listRemotes: (params: { type: number; page?: number; pageSize?: number }): Promise<unknown> => this._call("ir.listRemotes", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    matchRemote: (params: { irData: string; irType: number; brandName?: string }): Promise<unknown> => this._call("ir.matchRemote", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    renameKey: (params: { remote: string; key: string; newName: string }): Promise<unknown> => this._call("ir.renameKey", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    renameRemote: (params: { remote: string; alias: string }): Promise<unknown> => this._call("ir.renameRemote", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    searchRemotes: (params: { type: number; searchTerm: string }): Promise<unknown> => this._call("ir.searchRemotes", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    send: (params: { remote?: string; key: string }): Promise<unknown> => this._call("ir.send", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    setMode: (params: { hub3?: string; mode: number }): Promise<unknown> => this._call("ir.setMode", params) as Promise<unknown>,
  };

  readonly lock = {
    click: (params: { name?: string; deviceUUID?: string; secretKey?: string; scriptIndex?: number }): Promise<{ action: string; code?: number; success?: boolean; message?: string; op?: string; data?: unknown }> => this._call("lock.click", params) as Promise<{ action: string; code?: number; success?: boolean; message?: string; op?: string; data?: unknown }>,
    lock: (params: { name?: string; deviceUUID?: string; secretKey?: string }): Promise<{ action: string; code?: number; success?: boolean; message?: string; op?: string; data?: unknown }> => this._call("lock.lock", params) as Promise<{ action: string; code?: number; success?: boolean; message?: string; op?: string; data?: unknown }>,
    /** @experimental unverified — may change without notice. */
    setAutolock: (params: { name?: string; deviceUUID?: string; secretKey?: string; seconds: number; timeoutMs?: number; transport?: "cloud" | "ble"; address?: string; model?: string; scanTimeoutMs?: number; debug?: boolean }): Promise<unknown> => this._call("lock.setAutolock", params) as Promise<unknown>,
    status: (params: { deviceUUID: string }): Promise<{ deviceUUID: string; deviceName?: string; deviceModel?: string; secretKey?: string; keyLevel?: number; rank?: number; stateInfo?: unknown } | null> => this._call("lock.status", params) as Promise<{ deviceUUID: string; deviceName?: string; deviceModel?: string; secretKey?: string; keyLevel?: number; rank?: number; stateInfo?: unknown } | null>,
    toggle: (params: { name?: string; deviceUUID?: string; secretKey?: string }): Promise<{ action: string; code?: number; success?: boolean; message?: string; op?: string; data?: unknown }> => this._call("lock.toggle", params) as Promise<{ action: string; code?: number; success?: boolean; message?: string; op?: string; data?: unknown }>,
    unlock: (params: { name?: string; deviceUUID?: string; secretKey?: string }): Promise<{ action: string; code?: number; success?: boolean; message?: string; op?: string; data?: unknown }> => this._call("lock.unlock", params) as Promise<{ action: string; code?: number; success?: boolean; message?: string; op?: string; data?: unknown }>,
  };

  readonly org = {
    /** @experimental unverified — may change without notice. */
    addDeviceGroup: (params: { companyID?: string; name: string; uuids: Array<string>; timeoutMs?: number }): Promise<unknown> => this._call("org.addDeviceGroup", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    addDeviceInGroup: (params: { companyID?: string; gid: string; uuids: Array<unknown>; items: Array<unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.addDeviceInGroup", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    addEmployeeGroup: (params: { companyID?: string; item: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.addEmployeeGroup", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    addEmployeeInGroup: (params: { companyID?: string; gid: string; uuids: Array<unknown>; items: Array<unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.addEmployeeInGroup", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    addEmployees: (params: { items: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("org.addEmployees", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    confirmQueryByCS: (params: { email: string; timeoutMs?: number }): Promise<unknown> => this._call("org.confirmQueryByCS", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    generateGuestQR: (params: { data: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.generateGuestQR", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getCurrentUserInfo: (params: { timeoutMs?: number }): Promise<unknown> => this._call("org.getCurrentUserInfo", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getDeviceEmployeeKeys: (params: { deviceUUID: string; companyID?: string; limit?: number; timeoutMs?: number }): Promise<unknown> => this._call("org.getDeviceEmployeeKeys", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getDeviceGroupBindUserGroup: (params: { gid: string; timeoutMs?: number }): Promise<unknown> => this._call("org.getDeviceGroupBindUserGroup", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getDeviceGroups: (params: { companyID?: string; timeoutMs?: number }): Promise<unknown> => this._call("org.getDeviceGroups", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getEmployeeDeviceKeys: (params: { subUUID?: string; timeoutMs?: number }): Promise<unknown> => this._call("org.getEmployeeDeviceKeys", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getEmployeeGroupBindDeviceGroup: (params: { gid: string; timeoutMs?: number }): Promise<unknown> => this._call("org.getEmployeeGroupBindDeviceGroup", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getEmployeeGroups: (params: { companyID?: string; timeoutMs?: number }): Promise<unknown> => this._call("org.getEmployeeGroups", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getEmployees: (params: { companyID?: string; timeoutMs?: number; partialOnTimeout?: boolean }): Promise<unknown> => this._call("org.getEmployees", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getTags: (params: { companyID?: string; timeoutMs?: number }): Promise<unknown> => this._call("org.getTags", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    postTag: (params: { companyID?: string; data: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.postTag", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    queryByCS: (params: { keyword: string; timeoutMs?: number; partialOnTimeout?: boolean }): Promise<unknown> => this._call("org.queryByCS", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    removeDeviceGroupBindUserGroup: (params: { companyID?: string; data: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeDeviceGroupBindUserGroup", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    removeDeviceGroups: (params: { companyID?: string; groupIds: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeDeviceGroups", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    removeDeviceInGroup: (params: { companyID?: string; gid: string; uuids: Array<unknown>; items: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeDeviceInGroup", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    removeEmployeeDeviceKey: (params: { data: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeEmployeeDeviceKey", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    removeEmployeeGroupBindDeviceGroup: (params: { companyID?: string; data: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeEmployeeGroupBindDeviceGroup", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    removeEmployeeGroups: (params: { companyID?: string; gids: Array<unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeEmployeeGroups", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    removeEmployeeInGroup: (params: { companyID?: string; gid: string; uuids: Array<unknown>; items: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeEmployeeInGroup", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    removeEmployees: (params: { items: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeEmployees", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    removeTag: (params: { companyID?: string; data: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.removeTag", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    reorderEmployees: (params: { items: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("org.reorderEmployees", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    shareDeviceGroupKeysToEmployeeGroup: (params: { companyID?: string; item: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.shareDeviceGroupKeysToEmployeeGroup", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    shareDeviceKeysToEmployees: (params: { items: Array<Record<string, unknown>>; timeoutMs?: number }): Promise<unknown> => this._call("org.shareDeviceKeysToEmployees", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    updateDeviceGroup: (params: { companyID?: string; item: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.updateDeviceGroup", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    updateEmployee: (params: { companyID?: string; data: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.updateEmployee", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    updateEmployeeGroup: (params: { companyID?: string; item: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.updateEmployeeGroup", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    updateGuestKeyTag: (params: { data: Record<string, unknown>; timeoutMs?: number }): Promise<unknown> => this._call("org.updateGuestKeyTag", params) as Promise<unknown>,
  };

  readonly payment = {
    /** @experimental unverified — may change without notice. */
    changeDefaultPayment: (params: { customerId?: string; companyID?: string; defaultPaymentMethod?: string; timeoutMs?: number }): Promise<unknown> => this._call("payment.changeDefaultPayment", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getClientSecret: (params: { customerId?: string; companyID?: string; timeoutMs?: number }): Promise<unknown> => this._call("payment.getClientSecret", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getDevApiInfo: (params: { customerId?: string; companyID?: string; email?: string; update?: boolean; timeoutMs?: number }): Promise<unknown> => this._call("payment.getDevApiInfo", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getPaymentMethods: (params: { customerId?: string; companyID?: string; timeoutMs?: number }): Promise<unknown> => this._call("payment.getPaymentMethods", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    payUpdateLevel: (params: { customerId?: string; companyID?: string; subId?: string; subscriptionId?: string; level?: number; isUpgrade?: boolean; isCancel?: boolean; timeoutMs?: number }): Promise<unknown> => this._call("payment.payUpdateLevel", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    removePayment: (params: { customerId?: string; companyID?: string; paymentId?: string; timeoutMs?: number }): Promise<unknown> => this._call("payment.removePayment", params) as Promise<unknown>,
  };

  readonly presetir = {
    /** @experimental unverified — may change without notice. */
    emitAir: (params: { deviceId: string; companyID?: string; code: number; irDeviceUUID?: string; timeoutMs?: number; savedState?: string; power?: boolean; temperature?: number; mode?: number; fanSpeed?: number; windDirection?: number; autoSwing?: boolean; keyType?: string }): Promise<unknown> => this._call("presetir.emitAir", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    emitButton: (params: { deviceId: string; companyID?: string; code: number; irType: number; buttonType: string; irDeviceUUID?: string; timeoutMs?: number }): Promise<unknown> => this._call("presetir.emitButton", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    sendIR: (params: { deviceId: string; command: string; irType: number; companyID?: string; irDeviceUUID?: string; operation?: string; timeoutMs?: number }): Promise<unknown> => this._call("presetir.sendIR", params) as Promise<unknown>,
  };

  readonly rpc = {
    discover: (): Promise<unknown> => this._call("rpc.discover", {}) as Promise<unknown>,
  };

  readonly schedule = {
    /** @experimental unverified — may change without notice. */
    cancelSchedule: (params: { subUUID?: string; scheduleId?: string; timeoutMs?: number }): Promise<unknown> => this._call("schedule.cancelSchedule", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    getScheduleList: (params: { subUUID?: string; timeoutMs?: number }): Promise<unknown> => this._call("schedule.getScheduleList", params) as Promise<unknown>,
  };

  readonly webapi = {
    /** @experimental unverified — may change without notice. */
    deviceHistory: (params: { deviceId: string; page?: number; lg?: number; isBiz?: boolean; apiKeyId?: string }): Promise<unknown> => this._call("webapi.deviceHistory", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    deviceState: (params: { deviceId: string; apiKeyId?: string }): Promise<unknown> => this._call("webapi.deviceState", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    invoke: (params: { func: string; query?: Record<string, unknown>; body?: Record<string, unknown>; apiKeyId?: string }): Promise<unknown> => this._call("webapi.invoke", params) as Promise<unknown>,
    /** @experimental unverified — may change without notice. */
    sendCmd: (params: { deviceId: string; cmd: number; sign: string; history: string; apiKeyId?: string }): Promise<unknown> => this._call("webapi.sendCmd", params) as Promise<unknown>,
  };
}
